apiVersion: v1
kind: Service
metadata:
  name: container-scan-app
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: container-scan
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: container-scan
    app.kubernetes.io/component: app
