apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: container-scan
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: my-release
    statefulset.kubernetes.io/pod-name: my-release-postgresql-0
