---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: container-scan-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: container-scan-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: container-scan-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: container-scan-sa
    namespace: default
roleRef:
  kind: Role
  name: container-scan-role
  apiGroup: rbac.authorization.k8s.io
